name: Simple Workflow

on:
  push:
    branches:
      - main
      - feature1
      
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List project files
        run: ls -la
